[application]

[web.app]

# HTML title tag content
title = "get_the_album"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
  "/assets/tailwind.css",
  "/assets/styling/main.css",
  "/assets/styling/song.css",
  "/assets/styling/album.css",
  "/assets/styling/comments.css",
  "/assets/styling/footer.css",
  "/assets/styling/navbar.css",
  "/assets/styling/terms.css",
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

# Configure the server to handle client-side routing
[web.app.server]
fallback = "index.html"
